album/urls.py
from django.urls import path

from .serializers import AlbumView
from .views import handle_album, index

app_name = "album"

urlpatterns = [
    path('<str:sort_key>', index, name='index'),
    path('', index, name='index'),
    path('api/', handle_album, name='create_album'),
    path('api/sort/', AlbumView.as_view(), name='get_album'),
]

music_albums/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('album.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

album/models.py
from django.db import models


class Artist(models.Model):
    name = models.CharField(
        verbose_name="Имя",
        max_length=200,
    )

    class Meta:
        verbose_name = 'Артист'
        verbose_name_plural = 'Артисты'

    def __str__(self):
        return self.name


class Album(models.Model):
    name = models.CharField(
        verbose_name="Название",
        max_length=200,
    )
    artist = models.ForeignKey(
        Artist,
        on_delete=models.CASCADE,
        verbose_name="Артист",
        related_name='albums',
    )
    year = models.PositiveIntegerField(
        verbose_name='Год'
    )

    class Meta:
        verbose_name = 'Альбом'
        verbose_name_plural = 'Альбомы'

    def __str__(self):
        return f'{self.name}[{self.year}]'


class Track(models.Model):
    name = models.CharField(
        verbose_name="Название",
        max_length=200,
    )
    album = models.ForeignKey(
        Album,
        on_delete=models.CASCADE,
        verbose_name="Альбом",
        related_name='tracks',
    )

    class Meta:
        verbose_name = 'Трек'
        verbose_name_plural = 'Треки'

    def __str__(self):
        return self.name

album/views.py
import re

import requests
from django.shortcuts import render
from django.urls import reverse_lazy
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Album, Artist, Track
from .serializers import AlbumSerializer


def get_year_by_album(album: str) -> int:
    """Return year from AlbumField like 'album[int:year]'"""
    pattern = r'\[(\d+)\]'
    year = re.search(pattern, album).group(1)
    return int(year)


@api_view(['GET', 'POST'])
def handle_album(request) -> Response:
    """API endpoint with serialize album"""
    if request.method == 'GET':
        albums = Album.objects.all().select_related('artist').prefetch_related(
            'tracks')
        serialize_albums = AlbumSerializer(albums, many=True)
        return Response(serialize_albums.data)
    if request.method == 'POST':
        serializer = AlbumSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        artist, created = Artist.objects.get_or_create(
            name=serializer.validated_data['artist@name']
        )
        album = Album.objects.create(
            name=serializer.validated_data['name'],
            artist=artist,
            year=get_year_by_album(serializer.validated_data['album'])
        )
        for track in serializer.validated_data['tracks']:
            Track.objects.create(
                name=track,
                album=album
            )
        return Response(serializer.validated_data)


def index(request, sort_key='') -> render:
    """Render main page with albums from db with API"""
    payload = {"ordering": sort_key}
    url = request.build_absolute_uri(reverse_lazy('album:get_album'))
    response = requests.get(url, params=payload)
    response.raise_for_status()
    decoded_response = response.json()
    try:
        captions = decoded_response[0].keys()
    except IndexError:
        captions = []

    context = {'albums': decoded_response, 'captions': captions}
    return render(request, 'album/index.html', context=context)

album/templates/album/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Albums</title>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
</head>
<body>

{% block content %}
{% endblock content %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

album/templates/album/index.html
{% extends "album/base.html" %}
{% block content %}
<table class="table w-50 p-3" style="margin: auto;">
    <tr>
        {% for caption in captions %}

        <th scope="col">

            {{ caption }}
            {% if caption == 'name' %}
            <br>
            <button type="button" class="btn btn-outline-dark btn-sm"
                    onclick="window.location.href = '{% url 'album:index' sort_key=caption%}'">
                sort
            </button>
            {% elif caption == 'artist@name' %}
            <br>
            <button type="button" class="btn btn-outline-dark btn-sm"
                    onclick="window.location.href = '{% url 'album:index' sort_key='artist'%}'">
                sort
            </button>
            {% endif %}

        </th>
        {% endfor %}
    </tr>

    {% for album in albums %}
    <tr>
        {% for key, value in album.items %}
        {% if key == 'tracks' %}
        <td>
            <ul class="list-group list-group-flush">
                {% for track in value %}
                <li class="list-group-item">{{ track }}</li>
                {% endfor %}
            </ul>
            {% else %}
        <td>{{ value }}</td>
        {% endif %}

        {% endfor %}

    </tr>
    {% endfor %}
</table>
{% endblock content %}